#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


echo 'Running tests...';
npm run test || (
    echo '❌👷🔨❌ Some tests are failing ❌👷🔨❌. Please, solve them, and try again.'
);

echo 'Building project...';
npm run build || (
    echo '❌👷🔨❌  The build failed. ❌👷🔨❌. Please, solve the issues, and try again.'
);

echo '✅ Looks good to me. ✅';
