#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Checking code standards before commiting...';

echo 'Formatting code...';
npx prettier --write .;

echo 'Checking code format...';
npm run check-format || (
    echo '❌👷🔨❌ There are some formatting issues. Please, solve them, and try again.';
    false;
);

echo 'Fixing linting issues...';

npm run lint;

# Staging changes
git add .;

echo 'Checking linting issues...';
npm run check-lint ||
(
        echo '❌👷🔨❌ Linting issues found. Please, solve them, and try again.';
        false; 
);

# echo 'Running tests...';
# npm run test || (
#     echo '❌👷🔨❌ Some tests are failing ❌👷🔨❌. Please, solve them, and try again.';
#     false;
# );

echo 'Checking type issues...';
npm run check-types || (
    echo '❌👷🔨❌ There are some type issues. Please, solve them, and try again.'
    false;
);

echo '✅ Looks good to me. ✅';
