#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


# echo 'Running tests...';
# npm run test || (
#     echo '❌👷🔨❌ Some tests are failing ❌👷🔨❌. Please, solve them, and try again.'
# );

echo 'Checking code format...';
npm run check-format || (
    echo '❌👷🔨❌ There are some formatting issues. Please, solve them, and try again.';
    false;
);

echo 'Fixing linting issues...';

npm run lint;

# Staging changes

echo 'Checking linting issues...';
npm run check-lint ||
(
        echo '❌👷🔨❌ Linting issues found. Please, solve them, and try again.';
        false; 
);

# echo 'Running tests...';
# npm run test || (
#     echo '❌👷🔨❌ Some tests are failing ❌👷🔨❌. Please, solve them, and try again.';
#     false;
# );

echo 'Checking type issues...';
npm run check-types || (
    echo '❌👷🔨❌ There are some type issues. Please, solve them, and try again.'
    false;
);

echo 'Building project...';
npm run build || (
    echo '❌👷🔨❌  The build failed. ❌👷🔨❌. Please, solve the issues, and try again.'
);

echo '✅ Looks good to me. ✅';
